### ISSUE TITLE
Feedback for unable to access table “pdpr_dapil_calon_list”

### ISSUE THREAD

**Issue by amirul-m** [zakiego/pantau-pemilu-2024-docs#4]
Access denied when access table "pdpr_dapil_calon_list"

<img width="576" alt="image" src="https://github.com/zakiego/pantau-pemilu-2024-docs/assets/45891982/70f0c7c9-af5d-4ad7-aa76-abd6227ce8e1">

**Comment by zakiego** [comment]
I've fixed this issue, you can try again (https://data-pemilu.vercel.app/changelog#5-maret-2024)
